### ISSUE TITLE
Quiz Clock Error

### ISSUE THREAD

**Issue by average-fox** [wwwLulu/Trivia.io#1]
After adding the name and the room name, The program works perfectly well.
However refreshing to the page and after navigating back to "Generate Quiz", the program's clock speed increases  by 2. Next refresh makes the clock even more  increased in time. After a few refreshes, the clock itself speeds at such limit that it is impossible to have enough time to give a answer.

Please note that this problem arises when the user enters the same credentials on the home page.

**Comment by wwwLulu** [comment]
Fixed the issue, try it again.
